# Generated by Django 4.0.6 on 2022-07-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='abount',
            field=models.TextField(),
        ),
    ]
