# Generated by Django 4.0.6 on 2022-09-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_post_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
