# Generated by Django 4.0.6 on 2022-10-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0013_ipmodel_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
