# Generated by Django 4.0.6 on 2022-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0002_coverpic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpic',
            name='choices',
            field=models.CharField(choices=[('ch1', 'อ่านต่อที่นี่'), ('ch2', 'สมัครที่นี่'), ('ch3', 'คลิ๊ก'), ('ch4', 'เพิ่มเติม')], default='ch3', max_length=3),
        ),
    ]
