# Generated by Django 4.0.6 on 2022-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0003_coverpic_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverpic',
            name='choices',
            field=models.CharField(choices=[('อ่านต่อที่นี่', 'อ่านต่อที่นี่'), ('สมัครที่นี่', 'สมัครที่นี่'), ('คลิ๊ก', 'คลิ๊ก'), ('เพิ่มเติม', 'เพิ่มเติม')], default='คลิ๊ก', max_length=50),
        ),
    ]
