# Generated by Django 4.0.6 on 2022-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0004_alter_coverpic_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverpic',
            name='choices',
            field=models.CharField(max_length=50),
        ),
    ]
