# Generated by Django 4.0.6 on 2022-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0005_alter_coverpic_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpic',
            name='vdolink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
