# Generated by Django 4.0.6 on 2022-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0006_coverpic_vdolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverpic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
