# Generated by Django 4.0.6 on 2022-09-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0008_remove_coverpic_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverpic',
            name='body',
        ),
    ]
